import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { redirect } from "next/navigation";

import { Layout } from "@/app/_components/layout";
import { Routes } from "@/config/routes";
import { auth } from "@/server/auth";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const isAuth = !!(await auth());
  if (!isAuth) {
    redirect(Routes.auth.signin);
  }

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <Layout>{children}</Layout>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
